force-app/main/default/objects/Clan__c/Clan__c.object-meta.xml
<CustomObject>
    <description>Clan object</description>
    <label>Clan</label>
    <nameField>
        <label>Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WarClan__c/WarClan__c.object-meta.xml
<CustomObject>
    <label>War Clan</label>
    <nameField>
        <label>War Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>War Clans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarClan__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan</label>
    <referenceTo>Clan__c</referenceTo>
    <relationshipLabel>War Clans</relationshipLabel>
    <relationshipName>WarClans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WarClanHandler.cls
public with sharing class WarClanHandler extends TriggerHandler {
    private Map<String, Clan__c> clanMap = new Map<String, Clan__c>();

    public override void bulkBefore() {
        Set<String> clanTags = new Set<String>();
        for (WarClan__c warClan : (List<WarClan__c>) Trigger.new) {
            clanTags.add(warClan.Tag__c);
        }

        List<Clan__c> clans = [SELECT Tag__c FROM Clan__c WHERE Tag__c IN :clanTags];
        for (Clan__c clan : clans) {
            this.clanMap.put(clan.Tag__c, clan);
        }
    }

    public override void beforeInsert(SObject so) {
        WarClan__c warClan = (WarClan__c) so;
        if (!this.clanMap.containsKey(warClan.Tag__c)) {
            return;
        }
        warClan.Clan__c = this.clanMap.get(warClan.Tag__c).Id;
    }
}