force-app/main/default/objects/Clan__c/Clan__c.object-meta.xml
<CustomObject>
    <description>Clan object</description>
    <label>Clan</label>
    <nameField>
        <label>Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanMember__c/ClanMember__c.object-meta.xml
<CustomObject>
    <label>Clan Member</label>
    <nameField>
        <label>Clan Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanMember__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <label>Clan</label>
    <referenceTo>Clan__c</referenceTo>
    <relationshipLabel>Clan Members</relationshipLabel>
    <relationshipName>ClanMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanMember__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWar__c/ClanWar__c.object-meta.xml
<CustomObject>
    <label>Clan War</label>
    <nameField>
        <displayFormat>WAR-{0000}</displayFormat>
        <label>Clan War Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Wars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWar__c/fields/AttacksPerMember__c.field-meta.xml
<CustomField>
    <fullName>AttacksPerMember__c</fullName>
    <label>Attacks per Member</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWar__c/fields/PreparationStartTime__c.field-meta.xml
<CustomField>
    <fullName>PreparationStartTime__c</fullName>
    <label>Preparation Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ClanWar__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>clanNotFound</fullName>
            </value>
            <value>
                <fullName>accessDenied</fullName>
            </value>
            <value>
                <fullName>notInWar</fullName>
            </value>
            <value>
                <fullName>inMatchmaking</fullName>
            </value>
            <value>
                <fullName>enterWar</fullName>
            </value>
            <value>
                <fullName>matched</fullName>
            </value>
            <value>
                <fullName>preparation</fullName>
            </value>
            <value>
                <fullName>war</fullName>
            </value>
            <value>
                <fullName>inWar</fullName>
            </value>
            <value>
                <fullName>ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClanWar__c/fields/TeamSize__c.field-meta.xml
<CustomField>
    <fullName>TeamSize__c</fullName>
    <label>Team Size</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWar__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>clan tag + opponent tag + preparation starttime</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/ClanWarAttack__c.object-meta.xml
<CustomObject>
    <label>Clan War Attack</label>
    <nameField>
        <displayFormat>ATCK-{00000}</displayFormat>
        <label>Clan War Attack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan War Attacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarAttack__c/fields/AttackerTag__c.field-meta.xml
<CustomField>
    <fullName>AttackerTag__c</fullName>
    <externalId>true</externalId>
    <label>Attacker Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/ClanWarMember__c.field-meta.xml
<CustomField>
    <fullName>ClanWarMember__c</fullName>
    <label>Clan War Member</label>
    <referenceTo>ClanWarMember__c</referenceTo>
    <relationshipLabel>Clan War Attacks</relationshipLabel>
    <relationshipName>ClanWarAttacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/DefenderTag__c.field-meta.xml
<CustomField>
    <fullName>DefenderTag__c</fullName>
    <externalId>true</externalId>
    <label>Defender Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/DestructionPercentage__c.field-meta.xml
<CustomField>
    <fullName>DestructionPercentage__c</fullName>
    <label>Destruction Percentage</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <inlineHelpText>in seconds</inlineHelpText>
    <label>Duration</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/Stars__c.field-meta.xml
<CustomField>
    <fullName>Stars__c</fullName>
    <label>Stars</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>clan war id + attacker tag + defender tag</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>38</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/ClanWarMember__c.object-meta.xml
<CustomObject>
    <label>Clan War Member</label>
    <nameField>
        <label>Clan War Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarMember__c/fields/ClanMember__c.field-meta.xml
<CustomField>
    <fullName>ClanMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan Member</label>
    <referenceTo>ClanMember__c</referenceTo>
    <relationshipLabel>Clan War Members</relationshipLabel>
    <relationshipName>ClanWarMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/fields/MapPosition__c.field-meta.xml
<CustomField>
    <fullName>MapPosition__c</fullName>
    <label>Map Position</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/fields/OpponentAttacks__c.field-meta.xml
<CustomField>
    <fullName>OpponentAttacks__c</fullName>
    <label>Opponent Attacks</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>war clan id + clan member tag</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>28</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/fields/WarClan__c.field-meta.xml
<CustomField>
    <fullName>WarClan__c</fullName>
    <label>War Clan</label>
    <referenceTo>WarClan__c</referenceTo>
    <relationshipLabel>Clan War Members</relationshipLabel>
    <relationshipName>ClanWarMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WarClan__c/WarClan__c.object-meta.xml
<CustomObject>
    <label>War Clan</label>
    <nameField>
        <label>War Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>War Clans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarClan__c/fields/Attacks__c.field-meta.xml
<CustomField>
    <fullName>Attacks__c</fullName>
    <label>Attacks</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan</label>
    <referenceTo>Clan__c</referenceTo>
    <relationshipLabel>War Clans</relationshipLabel>
    <relationshipName>WarClans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/ClanTag__c.field-meta.xml
<CustomField>
    <fullName>ClanTag__c</fullName>
    <externalId>true</externalId>
    <label>Clan Tag</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/ClanWar__c.field-meta.xml
<CustomField>
    <fullName>ClanWar__c</fullName>
    <label>Clan War</label>
    <referenceTo>ClanWar__c</referenceTo>
    <relationshipLabel>War Clans</relationshipLabel>
    <relationshipName>WarClans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/Stars__c.field-meta.xml
<CustomField>
    <fullName>Stars__c</fullName>
    <label>Stars</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>28</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClanWarSyncer.cls
public with sharing class ClanWarSyncer {
    public static void syncCurrentWar(String clanTag) {
        ClashOfClansClient client = new ClashOfClansClient();
        ClanWar currentWar = client.getClanCurrentWar(clanTag);

        List<Clan__c> opponentClans = [SELECT Id FROM Clan__c WHERE Tag__c = :currentWar.opponent.tag];
        if (opponentClans.size() > 1) {
            throw new ClashOfClansException('More than one clan with tag ' + currentWar.opponent.tag);
        }
        if (opponentClans.isEmpty()) {
            ClanSyncer.syncClan(currentWar.opponent.tag);
        }

        ClanWar__c currentWarSObject = generateClanWarSObject(currentWar);
        upsert currentWarSObject UniqueKey__c;

        WarClan__c clanWarClan = generateWarClan(currentWarSObject, currentWar.clan);
        WarClan__c opponentWarClan = generateWarClan(currentWarSObject, currentWar.opponent);
        upsert new List<WarClan__c>{ clanWarClan, opponentWarClan } UniqueKey__c;

        List<ClanWarMember__c> cwMembersToUpsert = new List<ClanWarMember__c>();
        for (ClanWar.ClanWarMember member : currentWar.clan.members) {
            cwMembersToUpsert.add(generateClanWarMember(clanWarClan, member));
        }
        for (ClanWar.ClanWarMember member : currentWar.opponent.members) {
            cwMembersToUpsert.add(generateClanWarMember(opponentWarClan, member));
        }
        upsert cwMembersToUpsert UniqueKey__c;

        List<ClanWarMember__c> queriedWarMembers = [
            SELECT ClanMember__r.Tag__c 
            FROM ClanWarMember__c 
            WHERE WarClan__r.ClanWar__c = :currentWarSObject.Id
        ];
        Map<String, ClanWarMember__c> clanWarMemberMap = new Map<String, ClanWarMember__c>();
        for (ClanWarMember__c warMember : queriedWarMembers) {
            clanWarMemberMap.put(warMember.ClanMember__r.Tag__c, warMember);
        }

        List<ClanWarAttack__c> cwAttacksToUpsert = new List<ClanWarAttack__c>();
        for (ClanWar.ClanWarMember member : currentWar.clan.members) {
            ClanWarMember__c clanWarMember = clanWarMemberMap.get(member.tag);
            for (ClanWar.ClanWarAttack attack : member.attacks) {
                cwAttacksToUpsert.add(generateClanWarAttack(clanWarMember, attack));
            }
        }
        upsert cwAttacksToUpsert UniqueKey__c;
    }

    private static ClanWar__c generateClanWarSObject(ClanWar currentWar) {
        ClanWar__c currentWarSObject = new ClanWar__c(
            State__c = currentWar.state,
            TeamSize__c = currentWar.teamSize,
            AttacksPerMember__c = currentWar.attacksPerMember,
            PreparationStartTime__c = currentWar.getPreparationStartTime(),
            StartTime__c = currentWar.getStartTime(),
            EndTime__c = currentWar.getEndTime(),
            UniqueKey__c = currentWar.clan.tag + currentWar.opponent.tag + currentWar.preparationStartTime
        );
        return currentWarSObject;
    }

    private static WarClan__c generateWarClan(ClanWar__c clanWarSObject, ClanWar.WarClan warClan) {
        WarClan__c warClanSObject = new WarClan__c(
            ClanWar__c = clanWarSObject.Id,
            Name = warClan.name,
            ClanTag__c = warClan.tag,
            DestructionPercentage__c = warClan.destructionPercentage,
            Stars__c = warClan.stars,
            Attacks__c = warClan.attacks,
            UniqueKey__c = clanWarSObject.Id + warClan.tag
        );

        return warClanSObject;
    }

    private static ClanWarMember__c generateClanWarMember(WarClan__c warClan, ClanWar.ClanWarMember clanWarMember) {
        ClanWarMember__c clanWarMemberSObj = new ClanWarMember__c(
            UniqueKey__c = warClan.Id + clanWarMember.tag,
            WarClan__c = warClan.Id,
            OpponentAttacks__c = clanWarMember.opponentAttacks,
            MapPosition__c = clanWarMember.mapPosition
        );
        return clanWarMemberSObj;
    }

    private static ClanWarAttack__c generateClanWarAttack(
        ClanWarMember__c clanWarMember, 
        ClanWar.ClanWarAttack clanWarAttack
    ) {
        ClanWarAttack__c clanWarAttackSObj = new ClanWarAttack__c(
            Duration__c = clanWarAttack.duration,
            Order__c = clanWarAttack.order,
            DestructionPercentage__c = clanWarAttack.destructionPercentage,
            Stars__c = clanWarAttack.stars,
            DefenderTag__c = clanWarAttack.defenderTag,
            AttackerTag__c = clanWarAttack.attackerTag,
            ClanWarMember__c = clanWarMember.Id
        );

        return clanWarAttackSObj;
    }
}