force-app/main/default/objects/ClanMember__c/ClanMember__c.object-meta.xml
<CustomObject>
    <label>Clan Member</label>
    <nameField>
        <label>Clan Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanMember__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/ClanWarMember__c.object-meta.xml
<CustomObject>
    <label>Clan War Member</label>
    <nameField>
        <label>Clan War Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarMember__c/fields/ClanMember__c.field-meta.xml
<CustomField>
    <fullName>ClanMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan Member</label>
    <referenceTo>ClanMember__c</referenceTo>
    <relationshipLabel>Clan War Members</relationshipLabel>
    <relationshipName>ClanWarMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClanWarMemberHandler.cls
public with sharing class ClanWarMemberHandler extends TriggerHandler {
    private Map<String, ClanMember__c> clanMemberMap = new Map<String, ClanMember__c>();

    public override void bulkBefore() {
        Set<String> memberTags = new Set<String>();
        for (ClanWarMember__c warMember : (List<ClanWarMember__c>) Trigger.new) {
            memberTags.add(warMember.Tag__c);
        }

        List<ClanMember__c> clanMembers = [SELECT Tag__c FROM ClanMember__c WHERE Tag__c IN :memberTags];
        for (ClanMember__c clanMember : clanMembers) {
            this.clanMemberMap.put(clanMember.Tag__c, clanMember);
        }
    }

    public override void beforeInsert(SObject so) {
        ClanWarMember__c warMember = (ClanWarMember__c) so;
        if (!this.clanMemberMap.containsKey(warMember.Tag__c)) {
            return;
        }

        warMember.ClanMember__c = this.clanMemberMap.get(warMember.Tag__c).Id;
    }
}