force-app/main/default/objects/ClanMember__c/ClanMember__c.object-meta.xml
<CustomObject>
    <label>Clan Member</label>
    <nameField>
        <label>Clan Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanMember__c/fields/Donations__c.field-meta.xml
<CustomField>
    <fullName>Donations__c</fullName>
    <label>Donations</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanMember__c/fields/DonationsReceived__c.field-meta.xml
<CustomField>
    <fullName>DonationsReceived__c</fullName>
    <label>Donations Received</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MemberDonationReset__e/MemberDonationReset__e.object-meta.xml
<CustomObject>
    <description>Event is fired whenever donations are reset (due to a new season)</description>
    <label>Member Donation Reset</label>
    <pluralLabel>Member Donation Resets</pluralLabel>
</CustomObject>

force-app/main/default/objects/MemberDonationReset__e/fields/ClanMemberId__c.field-meta.xml
<CustomField>
    <fullName>ClanMemberId__c</fullName>
    <label>Clan Member Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MemberDonationReset__e/fields/Donations__c.field-meta.xml
<CustomField>
    <fullName>Donations__c</fullName>
    <label>Donations</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MemberDonationReset__e/fields/DonationsReceived__c.field-meta.xml
<CustomField>
    <fullName>DonationsReceived__c</fullName>
    <label>Donations Received</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClanMemberHandler.cls
public with sharing class ClanMemberHandler extends TriggerHandler {
    private List<MemberDonationReset__e> memberDonationResets = new List<MemberDonationReset__e>();

    public override void afterUpdate(SObject oldSo, SObject newSo) {
        ClanMember__c oldClanMember = (ClanMember__c) oldSo;
        ClanMember__c newClanMember = (ClanMember__c) newSo;

        if (
            newClanMember.Donations__c < oldClanMember.Donations__c 
            || newClanMember.DonationsReceived__c < oldClanMember.DonationsReceived__c
        ) {
            memberDonationResets.add(new MemberDonationReset__e(
                ClanMemberId__c = oldClanMember.Id,
                Donations__c = oldClanMember.Donations__c,
                DonationsReceived__c = oldClanMember.DonationsReceived__c
            ));
        }
    }

    public override void andFinally() {
        Eventbus.publish(memberDonationResets);
    }
}