force-app/main/default/objects/ClanMember__c/ClanMember__c.object-meta.xml
<CustomObject>
    <label>Clan Member</label>
    <nameField>
        <label>Clan Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanMember__c/fields/Donations__c.field-meta.xml
<CustomField>
    <fullName>Donations__c</fullName>
    <label>Donations</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanMember__c/fields/DonationsReceived__c.field-meta.xml
<CustomField>
    <fullName>DonationsReceived__c</fullName>
    <label>Donations Received</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanMemberHistory__c/ClanMemberHistory__c.object-meta.xml
<CustomObject>
    <label>Clan Member History</label>
    <nameField>
        <label>Clan Member History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan Member Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanMemberHistory__c/fields/ClanMember__c.field-meta.xml
<CustomField>
    <fullName>ClanMember__c</fullName>
    <label>Clan Member</label>
    <referenceTo>ClanMember__c</referenceTo>
    <relationshipLabel>Clan Member Histories</relationshipLabel>
    <relationshipName>ClanMemberHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanMemberHistory__c/fields/Donations__c.field-meta.xml
<CustomField>
    <fullName>Donations__c</fullName>
    <label>Donations</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanMemberHistory__c/fields/DonationsReceived__c.field-meta.xml
<CustomField>
    <fullName>DonationsReceived__c</fullName>
    <label>Donations Received</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MemberDonationReset__e/MemberDonationReset__e.object-meta.xml
<CustomObject>
    <description>Event is fired whenever donations are reset (due to a new season)</description>
    <label>Member Donation Reset</label>
    <pluralLabel>Member Donation Resets</pluralLabel>
</CustomObject>

force-app/main/default/objects/MemberDonationReset__e/fields/ClanMemberId__c.field-meta.xml
<CustomField>
    <fullName>ClanMemberId__c</fullName>
    <label>Clan Member Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MemberDonationReset__e/fields/Donations__c.field-meta.xml
<CustomField>
    <fullName>Donations__c</fullName>
    <label>Donations</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MemberDonationReset__e/fields/DonationsReceived__c.field-meta.xml
<CustomField>
    <fullName>DonationsReceived__c</fullName>
    <label>Donations Received</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MemberDonationResetHandler.cls
public with sharing class MemberDonationResetHandler extends PlatformEventHandler {
    private List<ClanMemberHistory__c> memberHistoriesToInsert = new List<ClanMemberHistory__c>();

    public override void afterInsert(SObject so) {
        MemberDonationReset__e memberDonationReset = (MemberDonationReset__e) so;
        Id clanMemberId = (Id) memberDonationReset.ClanMemberId__c;
        memberHistoriesToInsert.add(new ClanMemberHistory__c(
            ClanMember__c = clanMemberId,
            Donations__c = memberDonationReset.Donations__c,
            DonationsReceived__c = memberDonationReset.DonationsReceived__c
        ));
    }

    public override void andFinally() {
        insert memberHistoriesToInsert;
    }
}