force-app/main/default/objects/ClanWar__c/ClanWar__c.object-meta.xml
<CustomObject>
    <label>Clan War</label>
    <nameField>
        <displayFormat>WAR-{0000}</displayFormat>
        <label>Clan War Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Wars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWar__c/fields/WarTag__c.field-meta.xml
<CustomField>
    <fullName>WarTag__c</fullName>
    <externalId>true</externalId>
    <label>War Tag</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/ClanWarLeagueRoundWar__c.object-meta.xml
<CustomObject>
    <label>Clan War League Round War</label>
    <nameField>
        <label>CWL Round War Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Round Wars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/fields/ClanWar__c.field-meta.xml
<CustomField>
    <fullName>ClanWar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan War</label>
    <referenceTo>ClanWar__c</referenceTo>
    <relationshipLabel>CWL Round Wars</relationshipLabel>
    <relationshipName>CWLRoundWars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/fields/WarTag__c.field-meta.xml
<CustomField>
    <fullName>WarTag__c</fullName>
    <externalId>true</externalId>
    <label>War Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClanWarHandler.cls
public with sharing class ClanWarHandler extends TriggerHandler {
    private Map<String, ClanWarLeagueRoundWar__c> roundWarMap = new Map<String, ClanWarLeagueRoundWar__c>();
    private List<ClanWarLeagueRoundWar__c> roundWarsToUpdate = new List<ClanWarLeagueRoundWar__c>();

    public override void bulkAfter() {
        Set<String> warTags = new Set<String>();
        for (ClanWar__c clanWar : (List<ClanWar__c>) Trigger.new) {
            warTags.add(clanWar.WarTag__c);
        }
        warTags.remove(null);

        List<ClanWarLeagueRoundWar__c> roundWars = [
            SELECT WarTag__c 
            FROM ClanWarLeagueRoundWar__c 
            WHERE WarTag__c IN :warTags
            AND ClanWar__c = null
        ];
        for (ClanWarLeagueRoundWar__c roundWar : roundWars) {
            this.roundWarMap.put(roundWar.WarTag__c, roundWar);
        }
    }

    public override void afterInsert(SObject so) {
        ClanWar__c clanWar = (ClanWar__c) so;

        if (String.isBlank(clanWar.WarTag__c)) return;
        if (!this.roundWarMap.containsKey(clanWar.WarTag__c)) return;

        ClanWarLeagueRoundWar__c roundWar = this.roundWarMap.get(clanWar.WarTag__c);
        roundWarsToUpdate.add(new ClanWarLeagueRoundWar__c(Id = roundWar.Id, ClanWar__c = clanWar.Id));
    }

    public override void afterUpdate(SObject oldSo, SObject newSo) {
        ClanWar__c clanWar = (ClanWar__c) newSo;

        if (String.isBlank(clanWar.WarTag__c)) return;
        if (!this.roundWarMap.containsKey(clanWar.WarTag__c)) return;

        ClanWarLeagueRoundWar__c roundWar = this.roundWarMap.get(clanWar.WarTag__c);
        roundWarsToUpdate.add(new ClanWarLeagueRoundWar__c(Id = roundWar.Id, ClanWar__c = clanWar.Id));
    }

    public override void andFinally() {
        update roundWarsToUpdate;
    }
}