force-app/main/default/objects/ClanWar__c/ClanWar__c.object-meta.xml
<CustomObject>
    <label>Clan War</label>
    <nameField>
        <displayFormat>WAR-{0000}</displayFormat>
        <label>Clan War Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Wars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWar__c/fields/WarTag__c.field-meta.xml
<CustomField>
    <fullName>WarTag__c</fullName>
    <externalId>true</externalId>
    <label>War Tag</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/ClanWarLeagueRoundWar__c.object-meta.xml
<CustomObject>
    <label>Clan War League Round War</label>
    <nameField>
        <label>CWL Round War Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Round Wars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/fields/ClanWar__c.field-meta.xml
<CustomField>
    <fullName>ClanWar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clan War</label>
    <referenceTo>ClanWar__c</referenceTo>
    <relationshipLabel>CWL Round Wars</relationshipLabel>
    <relationshipName>CWLRoundWars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/fields/WarTag__c.field-meta.xml
<CustomField>
    <fullName>WarTag__c</fullName>
    <externalId>true</externalId>
    <label>War Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClanWarSyncerBatch.cls
public with sharing class ClanWarSyncerBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT WarTag__c
            FROM ClanWarLeagueRoundWar__c
            WHERE ClanWar__c = null
            AND WarTag__c != null
        ]);
    }

    public void execute(Database.BatchableContext bc, List<ClanWarLeagueRoundWar__c> roundWars) {
        for (ClanWarLeagueRoundWar__c roundWar : roundWars) {
            ClanWarSyncer.syncClanWarLeagueWar(roundWar.WarTag__c);
        }
    }

    public void finish(Database.BatchableContext bc) {

    }
}