force-app/main/default/objects/ClanWar__c/ClanWar__c.object-meta.xml
<CustomObject>
    <label>Clan War</label>
    <nameField>
        <displayFormat>WAR-{0000}</displayFormat>
        <label>Clan War Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Wars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarAttack__c/ClanWarAttack__c.object-meta.xml
<CustomObject>
    <label>Clan War Attack</label>
    <nameField>
        <displayFormat>ATCK-{00000}</displayFormat>
        <label>Clan War Attack Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan War Attacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarAttack__c/fields/ClanWarMember__c.field-meta.xml
<CustomField>
    <fullName>ClanWarMember__c</fullName>
    <label>Clan War Member</label>
    <referenceTo>ClanWarMember__c</referenceTo>
    <relationshipLabel>Clan War Attacks</relationshipLabel>
    <relationshipName>ClanWarAttacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/Defender__c.field-meta.xml
<CustomField>
    <fullName>Defender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Defender</label>
    <referenceTo>ClanWarMember__c</referenceTo>
    <relationshipLabel>Clan War Defenses</relationshipLabel>
    <relationshipName>ClanWarDefenses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClanWarAttack__c/fields/DefenderTag__c.field-meta.xml
<CustomField>
    <fullName>DefenderTag__c</fullName>
    <externalId>true</externalId>
    <label>Defender Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/ClanWarMember__c.object-meta.xml
<CustomObject>
    <label>Clan War Member</label>
    <nameField>
        <label>Clan War Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarMember__c/fields/WarClan__c.field-meta.xml
<CustomField>
    <fullName>WarClan__c</fullName>
    <label>War Clan</label>
    <referenceTo>WarClan__c</referenceTo>
    <relationshipLabel>Clan War Members</relationshipLabel>
    <relationshipName>ClanWarMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WarClan__c/WarClan__c.object-meta.xml
<CustomObject>
    <label>War Clan</label>
    <nameField>
        <label>War Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>War Clans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarClan__c/fields/ClanWar__c.field-meta.xml
<CustomField>
    <fullName>ClanWar__c</fullName>
    <label>Clan War</label>
    <referenceTo>ClanWar__c</referenceTo>
    <relationshipLabel>War Clans</relationshipLabel>
    <relationshipName>WarClans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClanWarAttackHandler.cls
public with sharing class ClanWarAttackHandler extends TriggerHandler {
    private Map<String, ClanWarMember__c> defenderMap = new Map<String, ClanWarMember__c>();
    private Map<Id, ClanWarMember__c> attackIdToMember = new Map<Id, ClanWarMember__c>();

    public override void bulkBefore() {
        Set<Id> clanWarMemberIds = new Set<Id>();
        for (ClanWarAttack__c attack : (List<ClanWarAttack__c>) Trigger.new) {
            clanWarMemberIds.add(attack.ClanWarMember__c);
        }

        List<ClanWarMember__c> attackingMembers = [SELECT WarClan__r.ClanWar__c FROM ClanWarMember__c WHERE Id IN :clanWarMemberIds];
        Map<Id, ClanWarMember__c> attackingMemberMap = new Map<Id, ClanWarMember__c>(attackingMembers);
        Set<Id> clanWarIds = new Set<Id>();
        for (ClanWarMember__c attackingMember : attackingMembers) {
            clanWarIds.add(attackingMember.WarClan__r.ClanWar__c);
        }

        for (ClanWarAttack__c attack : (List<ClanWarAttack__c>) Trigger.new) {
            this.attackIdToMember.put(attack.Id, attackingMemberMap.get(attack.ClanWarMember__c));
        }

        Set<String> defenderTags = new Set<String>();
        for (ClanWarAttack__c attack : (List<ClanWarAttack__c>) Trigger.new) {
            defenderTags.add(attack.DefenderTag__c);
        }

        List<ClanWarMember__c> defendingMembers = [
            SELECT Tag__c, WarClan__r.ClanWar__c 
            FROM ClanWarMember__c 
            WHERE WarClan__r.ClanWar__c IN :clanWarIds 
            AND Tag__c IN :defenderTags
        ];
        for (ClanWarMember__c defendingMember : defendingMembers) {
            this.defenderMap.put(defendingMember.WarClan__r.ClanWar__c + '|' + defendingMember.Tag__c, defendingMember);
        }
    }

    public override void beforeInsert(SObject so) {
        ClanWarAttack__c attack = (ClanWarAttack__c) so;
        Id clanWarId = this.attackIdToMember.get(attack.Id).WarClan__r.ClanWar__c;
        Id defenderId = this.defenderMap.get(clanWarId + '|' + attack.DefenderTag__c).Id;
        attack.Defender__c = defenderId;
    }

    public override void beforeUpdate(SObject oldSo, SObject newSo) {
        ClanWarAttack__c attack = (ClanWarAttack__c) newSo;
        if (attack.Defender__c != null) {
            return;
        }
        Id clanWarId = this.attackIdToMember.get(attack.Id).WarClan__r.ClanWar__c;
        Id defenderId = this.defenderMap.get(clanWarId + '|' + attack.DefenderTag__c).Id;
        attack.Defender__c = defenderId;
    }
}