force-app/main/default/objects/ClanWar__c/ClanWar__c.object-meta.xml
<CustomObject>
    <label>Clan War</label>
    <nameField>
        <displayFormat>WAR-{0000}</displayFormat>
        <label>Clan War Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan Wars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarMember__c/ClanWarMember__c.object-meta.xml
<CustomObject>
    <label>Clan War Member</label>
    <nameField>
        <label>Clan War Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarMember__c/fields/MapPosition__c.field-meta.xml
<CustomField>
    <fullName>MapPosition__c</fullName>
    <label>Map Position</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/fields/OpponentAttacks__c.field-meta.xml
<CustomField>
    <fullName>OpponentAttacks__c</fullName>
    <label>Opponent Attacks</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/fields/TownHallLevel__c.field-meta.xml
<CustomField>
    <fullName>TownHallLevel__c</fullName>
    <label>Town Hall Level</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarMember__c/fields/WarClan__c.field-meta.xml
<CustomField>
    <fullName>WarClan__c</fullName>
    <label>War Clan</label>
    <referenceTo>WarClan__c</referenceTo>
    <relationshipLabel>Clan War Members</relationshipLabel>
    <relationshipName>ClanWarMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WarClan__c/WarClan__c.object-meta.xml
<CustomObject>
    <label>War Clan</label>
    <nameField>
        <label>War Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>War Clans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WarClan__c/fields/ClanWar__c.field-meta.xml
<CustomField>
    <fullName>ClanWar__c</fullName>
    <label>Clan War</label>
    <referenceTo>ClanWar__c</referenceTo>
    <relationshipLabel>War Clans</relationshipLabel>
    <relationshipName>WarClans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WarClan__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClanWarVersusViewController.cls
public with sharing class ClanWarVersusViewController {
    @AuraEnabled(cacheable=true)
    public static ClanWarDetails getWarDetails(Id clanWarId) {
        List<WarClan__c> warClans = [
            SELECT Name, 
                (
                    SELECT Name, 
                        Tag__c, 
                        OpponentAttacks__c, 
                        TownHallLevel__c 
                    FROM ClanWarMembers__r 
                    ORDER BY MapPosition__c
                ) 
            FROM WarClan__c 
            WHERE ClanWar__c = :clanWarId WITH SECURITY_ENFORCED
        ];
        if (warClans.size() != 2) {
            throw new ClashOfClansException('Did not find 2 war clans: ' + warClans.size());
        }

        ClanWarDetails details = new ClanWarDetails();
        details.clan = warClans[0];
        details.opponent = warClans[1];
        return details;
    }

    public class ClanWarDetails {
        @AuraEnabled public WarClan__c clan;
        @AuraEnabled public WarClan__c opponent;
    }
}