force-app/main/default/objects/ClanToSync__c/ClanToSync__c.object-meta.xml
<CustomObject>
    <label>Clan to Sync</label>
    <nameField>
        <displayFormat>SYNC-{0000}</displayFormat>
        <label>Clan to Sync Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clans to Sync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanToSync__c/fields/ClanTag__c.field-meta.xml
<CustomField>
    <fullName>ClanTag__c</fullName>
    <externalId>true</externalId>
    <label>Clan Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClanSyncerBatch.cls
public with sharing class ClanSyncerBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, System.Schedulable {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT ClanTag__c FROM ClanToSync__c]);
    }

    public void execute(Database.BatchableContext bc, List<SObject> records) {
        for (ClanToSync__c clansToSync : (List<ClanToSync__c>) records) {
            ClanSyncer.syncClan(clansToSync.ClanTag__c);
        }
    }

    public void finish(Database.BatchableContext bc) { }

    public void execute(System.SchedulableContext sc) {
        Database.executeBatch(new ClanSyncerBatch(), 1);
    }
}