force-app/main/default/objects/ClanWarLeagueClan__c/ClanWarLeagueClan__c.object-meta.xml
<CustomObject>
    <label>Clan War League Clan</label>
    <nameField>
        <label>Clan War League Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Clans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueClan__c/fields/ClanWarLeagueGroup__c.field-meta.xml
<CustomField>
    <fullName>ClanWarLeagueGroup__c</fullName>
    <label>Clan War League Group</label>
    <referenceTo>ClanWarLeagueGroup__c</referenceTo>
    <relationshipLabel>Clan War League Clans</relationshipLabel>
    <relationshipName>ClanWarLeagueClans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/ClanWarLeagueGroup__c.object-meta.xml
<CustomObject>
    <label>Clan War League Group</label>
    <nameField>
        <label>Clan War League Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/InitiatingClanTag__c.field-meta.xml
<CustomField>
    <fullName>InitiatingClanTag__c</fullName>
    <description>This is needed to differentiate clan war league groups since the tag is not available in the preparation state</description>
    <externalId>true</externalId>
    <label>Initiating Clan Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>groupNotFound</fullName>
            </value>
            <value>
                <fullName>notInWar</fullName>
            </value>
            <value>
                <fullName>preparation</fullName>
            </value>
            <value>
                <fullName>war</fullName>
            </value>
            <value>
                <fullName>ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>initiating clan tag + season</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClanWarLeagueSyncer.cls
public with sharing class ClanWarLeagueSyncer {
    public static void syncCurrentWarLeagueGroup(String clanTag) {
        ClashOfClansClient client = new ClashOfClansClient();
        ClanWarLeagueGroup warLeagueGroup = client.getCurrentWarLeagueGroup(clanTag);
        ClanWarLeagueGroup__c clanWarLeagueGroupSobj = generateClanWarLeagueGroupSObject(warLeagueGroup, clanTag);
        upsert clanWarLeagueGroupSobj UniqueKey__c;

        List<ClanWarLeagueClan__c> clanWarLeagueClans = 
            generateClanWarLeagueClans(clanWarLeagueGroupSobj, warLeagueGroup);


    }

    private static ClanWarLeagueGroup__c generateClanWarLeagueGroupSObject(
        ClanWarLeagueGroup warLeagueGroup,
        String initiatingClanTag
    ) {
        return new ClanWarLeagueGroup__c(
            Tag__c = warLeagueGroup.tag,
            State__c = warLeagueGroup.state,
            Season__c = warLeagueGroup.season,
            InitiatingClanTag__c = initiatingClanTag,
            UniqueKey__c = initiatingClanTag + warLeagueGroup.season
        );
    }

    private static List<ClanWarLeagueClan__c> generateClanWarLeagueClans(
        ClanWarLeagueGroup__c leagueGroupSObj, 
        ClanWarLeagueGroup leagueGroup
    ) {
        List<ClanWarLeagueClan__c> leagueClanSObjs = new List<ClanWarLeagueClan__c>();
        for (ClanWarLeagueGroup.ClanWarLeagueClan leagueClan : leagueGroup.clans) {
            leagueClanSObjs.add(new ClanWarLeagueClan__c(
                ClanLevel__c = leagueClan.clanLevel,
                Tag__c = leagueClan.tag,
                Name = leagueClan.name
            ));
        }
        return leagueClanSObjs;
    }
}