force-app/main/default/objects/ClanWarLeagueClan__c/ClanWarLeagueClan__c.object-meta.xml
<CustomObject>
    <label>Clan War League Clan</label>
    <nameField>
        <label>Clan War League Clan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Clans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueClan__c/fields/ClanWarLeagueGroup__c.field-meta.xml
<CustomField>
    <fullName>ClanWarLeagueGroup__c</fullName>
    <label>Clan War League Group</label>
    <referenceTo>ClanWarLeagueGroup__c</referenceTo>
    <relationshipLabel>Clan War League Clans</relationshipLabel>
    <relationshipName>ClanWarLeagueClans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueClanMember__c/ClanWarLeagueClanMember__c.object-meta.xml
<CustomObject>
    <label>Clan War League Clan Member</label>
    <nameField>
        <label>Clan Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Clan Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueClanMember__c/fields/ClanWarLeagueClan__c.field-meta.xml
<CustomField>
    <fullName>ClanWarLeagueClan__c</fullName>
    <label>Clan War League Clan</label>
    <referenceTo>ClanWarLeagueClan__c</referenceTo>
    <relationshipLabel>Clan War League Clan Members</relationshipLabel>
    <relationshipName>ClanWarLeagueClanMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueClanMember__c/fields/TownHallLevel__c.field-meta.xml
<CustomField>
    <fullName>TownHallLevel__c</fullName>
    <label>Town Hall Level</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueClanMember__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>clan war league clan id + player tag</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>28</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/ClanWarLeagueGroup__c.object-meta.xml
<CustomObject>
    <label>Clan War League Group</label>
    <nameField>
        <label>Clan War League Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/InitiatingClanTag__c.field-meta.xml
<CustomField>
    <fullName>InitiatingClanTag__c</fullName>
    <description>This is needed to differentiate clan war league groups since the tag is not available in the preparation state</description>
    <externalId>true</externalId>
    <label>Initiating Clan Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Season</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>groupNotFound</fullName>
            </value>
            <value>
                <fullName>notInWar</fullName>
            </value>
            <value>
                <fullName>preparation</fullName>
            </value>
            <value>
                <fullName>war</fullName>
            </value>
            <value>
                <fullName>ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <externalId>true</externalId>
    <label>Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueGroup__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>initiating clan tag + season</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRound__c/ClanWarLeagueRound__c.object-meta.xml
<CustomObject>
    <label>Clan War League Round</label>
    <nameField>
        <displayFormat>ROUND-{0000}</displayFormat>
        <label>Clan War League Round Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clan War League Rounds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueRound__c/fields/ClanWarLeagueGroup__c.field-meta.xml
<CustomField>
    <fullName>ClanWarLeagueGroup__c</fullName>
    <label>Clan War League Group</label>
    <referenceTo>ClanWarLeagueGroup__c</referenceTo>
    <relationshipLabel>Clan War League Rounds</relationshipLabel>
    <relationshipName>ClanWarLeagueRounds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRound__c/fields/RoundNumber__c.field-meta.xml
<CustomField>
    <fullName>RoundNumber__c</fullName>
    <label>Round Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRound__c/fields/WarTags__c.field-meta.xml
<CustomField>
    <fullName>WarTags__c</fullName>
    <externalId>true</externalId>
    <label>War Tags</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/ClanWarLeagueRoundWar__c.object-meta.xml
<CustomObject>
    <label>Clan War League Round War</label>
    <nameField>
        <label>CWL Round War Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clan War League Round Wars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/fields/ClanWarLeagueRound__c.field-meta.xml
<CustomField>
    <fullName>ClanWarLeagueRound__c</fullName>
    <label>Clan War League Round</label>
    <referenceTo>ClanWarLeagueRound__c</referenceTo>
    <relationshipLabel>CWL Round Wars</relationshipLabel>
    <relationshipName>CWLRoundWars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClanWarLeagueRoundWar__c/fields/WarTag__c.field-meta.xml
<CustomField>
    <fullName>WarTag__c</fullName>
    <externalId>true</externalId>
    <label>War Tag</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ClanWarLeagueGroupSyncer.cls
public with sharing class ClanWarLeagueGroupSyncer {
    @AuraEnabled
    public static void syncCurrentWar(String clanTag) {
        ClashOfClansClient client = new ClashOfClansClient();
        ClanWarLeagueGroup leagueGroup = client.getCurrentWarLeagueGroup(clanTag);
        ClanWarLeagueGroup__c leagueGroupToUpsert = generateLeagueGroupSObj(leagueGroup, clanTag);
        upsert leagueGroupToUpsert UniqueKey__c;

        List<ClanWarLeagueClan__c> clansToUpsert = generateClans(leagueGroupToUpsert, leagueGroup);
        upsert clansToUpsert UniqueKey__c;

        List<ClanWarLeagueClanMember__c> membersToUpsert = generateMembers(clansToUpsert, leagueGroup.clans);
        upsert membersToUpsert UniqueKey__c;

        List<ClanWarLeagueRound__c> roundsToUpsert = generateRounds(leagueGroupToUpsert, leagueGroup.rounds);
        upsert roundsToUpsert WarTags__c;

        List<ClanWarLeagueRoundWar__c> roundWarsToUpsert = generateRoundWars(roundsToUpsert);
        upsert roundWarsToUpsert WarTag__c;

        Database.executeBatch(new ClanWarSyncerBatch(), 1);
    }

    private static ClanWarLeagueGroup__c generateLeagueGroupSObj(
        ClanWarLeagueGroup warLeagueGroup,
        String initiatingClanTag
    ) {
        return new ClanWarLeagueGroup__c(
            Name = warLeagueGroup.season + ' ' + initiatingClanTag,
            Tag__c = warLeagueGroup.tag,
            State__c = warLeagueGroup.state,
            Season__c = warLeagueGroup.season,
            InitiatingClanTag__c = initiatingClanTag,
            UniqueKey__c = initiatingClanTag + warLeagueGroup.season
        );
    }

    private static List<ClanWarLeagueClan__c> generateClans(
        ClanWarLeagueGroup__c leagueGroupSObject, 
        ClanWarLeagueGroup leagueGroup
    ) {
        List<ClanWarLeagueClan__c> clanSObjects = new List<ClanWarLeagueClan__c>();
        for (ClanWarLeagueGroup.ClanWarLeagueClan leagueClan : leagueGroup.clans) {
            clanSObjects.add(new ClanWarLeagueClan__c(
                ClanWarLeagueGroup__c = leagueGroupSObject.Id,
                ClanLevel__c = leagueClan.clanLevel,
                Tag__c = leagueClan.tag,
                Name = leagueClan.name,
                UniqueKey__c = leagueGroupSObject.Id + leagueClan.tag
            ));
        }
        return clanSObjects;
    }

    private static List<ClanWarLeagueClanMember__c> generateMembers(
        List<ClanWarLeagueClan__c> clanSObjects, 
        List<ClanWarLeagueGroup.ClanWarLeagueClan> clans
    ) {
        Map<String, ClanWarLeagueClan__c> leagueClanMap = getLeagueClanMap(clanSObjects);

        List<ClanWarLeagueClanMember__c> membersToUpsert = new List<ClanWarLeagueClanMember__c>();
        for (ClanWarLeagueGroup.ClanWarLeagueClan clan : clans) {
            ClanWarLeagueClan__c clanSobj = leagueClanMap.get(clan.tag);

            for (ClanWarLeagueGroup.ClanWarLeagueClanMember member : clan.members) {
                membersToUpsert.add(new ClanWarLeagueClanMember__c(
                    ClanWarLeagueClan__c = clanSobj.Id,
                    TownHallLevel__c = member.townHallLevel,
                    Tag__c = member.tag,
                    Name = member.name,
                    UniqueKey__c = clanSobj.Id + member.tag
                ));
            }
        }

        return membersToUpsert;
    }

    private static Map<String, ClanWarLeagueClan__c> getLeagueClanMap(List<ClanWarLeagueClan__c> clanSobjs) {
        Map<String, ClanWarLeagueClan__c> leagueClanMap = new Map<String, ClanWarLeagueClan__c>();
        for (ClanWarLeagueClan__c clanSobj : clanSobjs) {
            leagueClanMap.put(clanSobj.Tag__c, clanSobj);
        }
        return leagueClanMap;
    }

    private static List<ClanWarLeagueRound__c> generateRounds(
        ClanWarLeagueGroup__c leagueGroupSObject, 
        List<ClanWarLeagueGroup.ClanWarLeagueRound> rounds
    ) {
        List<ClanWarLeagueRound__c> roundSObjects = new List<ClanWarLeagueRound__c>();
        for (Integer i = 0; i < rounds.size() - 1; i++) {
            ClanWarLeagueGroup.ClanWarLeagueRound round = rounds[i];
            if (round.warTags.contains('#0')) continue;

            roundSObjects.add(new ClanWarLeagueRound__c(
                RoundNumber__c = i + 1,
                ClanWarLeagueGroup__c = leagueGroupSObject.Id,
                WarTags__c = String.join(round.warTags, ';')
            ));
        }

        return roundSObjects;
    }

    private static List<ClanWarLeagueRoundWar__c> generateRoundWars(List<ClanWarLeagueRound__c> rounds) {
        List<ClanWarLeagueRoundWar__c> roundWars = new List<ClanWarLeagueRoundWar__c>();
        for (ClanWarLeagueRound__c round : rounds) {
            List<String> warTags = round.WarTags__c.split(';');
            for (String warTag : warTags) {
                roundWars.add(new ClanWarLeagueRoundWar__c(
                    ClanWarLeagueRound__c = round.Id,
                    WarTag__c = warTag
                ));
            }
        }
        return roundWars;
    }
}